trigger: 
  - main 

pool:
  vmImage: 'Ubuntu-latest'

variables:
  pythonVersion: "3.12"

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: Buildjob
        displayName: 'Build flask app'
        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python $(pythonVersion)'
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - task: ArchiveFiles@2
            displayName: 'Archive zip application'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            displayName: 'Publish artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/app.zip'
              artifact: 'flaskapp'
              publishLocation: 'pipeline'
  
  - stage: DeployStaging
    displayName: 'Deploy to Staging'
    dependsOn: Build
    condition: succeeded()
    jobs: 
      - deployment: DeployStagingJob
        displayName: 'Deploy Flask app to staging'
        environment: 'Staging'
        strategy: 
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy to App Service (staging)'
                  inputs:
                    azureSubscription: 'azure-flaskapp-cicd'
                    appType: 'webAppLinux'
                    appName: '$(stagingAppName)'
                    package: '$(Pipeline.Workspace)/flask-app/app.zip'
                    runtimeStack: 'PYTHON|3.12'
                    startUpCommand: 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'

